/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace CertificateRegistry {
  export type CertificateStruct = {
    name: string;
    matricNumber: string;
    department: string;
    classOfDegree: string;
    date: string;
    isRegistered: boolean;
    issuer: AddressLike;
  };

  export type CertificateStructOutput = [
    name: string,
    matricNumber: string,
    department: string,
    classOfDegree: string,
    date: string,
    isRegistered: boolean,
    issuer: string
  ] & {
    name: string;
    matricNumber: string;
    department: string;
    classOfDegree: string;
    date: string;
    isRegistered: boolean;
    issuer: string;
  };
}

export interface CertificateRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "certificates"
      | "issueCertificate"
      | "owner"
      | "verifyCertificate"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "CertificateIssued"): EventFragment;

  encodeFunctionData(
    functionFragment: "certificates",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "issueCertificate",
    values: [string, string, string, string, string, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyCertificate",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "certificates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyCertificate",
    data: BytesLike
  ): Result;
}

export namespace CertificateIssuedEvent {
  export type InputTuple = [
    referenceId: string,
    name: string,
    matricNumber: string,
    issuer: AddressLike
  ];
  export type OutputTuple = [
    referenceId: string,
    name: string,
    matricNumber: string,
    issuer: string
  ];
  export interface OutputObject {
    referenceId: string;
    name: string;
    matricNumber: string;
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CertificateRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CertificateRegistry;
  waitForDeployment(): Promise<this>;

  interface: CertificateRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  certificates: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, string, string, boolean, string] & {
        name: string;
        matricNumber: string;
        department: string;
        classOfDegree: string;
        date: string;
        isRegistered: boolean;
        issuer: string;
      }
    ],
    "view"
  >;

  issueCertificate: TypedContractMethod<
    [
      _ref: string,
      _name: string,
      _matricNumber: string,
      _department: string,
      _classOfDegree: string,
      _date: string
    ],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  verifyCertificate: TypedContractMethod<
    [_ref: string],
    [CertificateRegistry.CertificateStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "certificates"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, string, string, boolean, string] & {
        name: string;
        matricNumber: string;
        department: string;
        classOfDegree: string;
        date: string;
        isRegistered: boolean;
        issuer: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "issueCertificate"
  ): TypedContractMethod<
    [
      _ref: string,
      _name: string,
      _matricNumber: string,
      _department: string,
      _classOfDegree: string,
      _date: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyCertificate"
  ): TypedContractMethod<
    [_ref: string],
    [CertificateRegistry.CertificateStructOutput],
    "view"
  >;

  getEvent(
    key: "CertificateIssued"
  ): TypedContractEvent<
    CertificateIssuedEvent.InputTuple,
    CertificateIssuedEvent.OutputTuple,
    CertificateIssuedEvent.OutputObject
  >;

  filters: {
    "CertificateIssued(string,string,string,address)": TypedContractEvent<
      CertificateIssuedEvent.InputTuple,
      CertificateIssuedEvent.OutputTuple,
      CertificateIssuedEvent.OutputObject
    >;
    CertificateIssued: TypedContractEvent<
      CertificateIssuedEvent.InputTuple,
      CertificateIssuedEvent.OutputTuple,
      CertificateIssuedEvent.OutputObject
    >;
  };
}
